# Generated by Django 5.1 on 2024-08-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="data_entrega",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="data_finalizacao",
            field=models.DateField(null=True),
        ),
    ]
